name: CD
on:
  push:
    branches:
    - main
    - master
    
jobs:
  docker-build:
      runs-on: ubuntu-20.04
      steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: a891/vaccinebot:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  compile-host-manager:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Setup Deno
        uses: denoland/setup-deno@v1.1.0
        with:
          deno-version: vx.x.x
      -
        name: Compile linux
        run: deno compile --output host-manager-linux-x86_64 --target x86_64-unknown-linux-gnu --unstable --allow-read --allow-write --allow-net ./host-manager/index.ts
      -
        name: Compile Windows
        run: deno compile --output host-manager-windows-x86_64 --target x86_64-pc-windows-msvc --unstable --allow-read --allow-write --allow-net ./host-manager/index.ts
      -
        name: Compile Apple Darwin
        run: deno compile --output host-manager-darwin-x86_64 --target x86_64-apple-darwin --unstable --allow-read --allow-write --allow-net ./host-manager/index.ts
      - 
        name: Release to Github
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.sha }}
          files: |
            host-manager-linux-x86_64
            host-manager-windows-x86_64.exe
            host-manager-darwin-x86_64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}