name: Lint python

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-cache-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-cache-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install pytest wheel prospector

    - name: Lint via prospector
      run: python -m prospector
