# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on: [push, pull_request]

jobs:
  Windows-Build:

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest wheel
        python -m pip install -r requirements.txt
        python -m pip install nuitka zstandard

    - name: Make OneFile
      run: |
        nuitka --assume-yes-for-downloads --verbose --no-progress --include-data-file="./*.mp3=./" --onefile -o vaccine-run-kakao.exe vaccine-run-kakao.py
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
          name: Windows-Binary
          path: vaccine-run-kakao.exe


  MacOS-Build:

    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest wheel
        python -m pip install -r requirements.txt -r requirements-mac.txt -r requirements-dev.txt
    - name: Make OneFile
      run: |
        pyinstaller --add-data "*.mp3:." --onefile vaccine-run-kakao.py
        chmod +x dist/vaccine-run-kakao
    - name: Tar file
      run: tar -cvf dist/vaccine-run-kakao.tar dist/vaccine-run-kakao
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
          name: Mac-Binary
          path: dist/vaccine-run-kakao.tar